[window]
decorations = "full"
opacity = 0.8
  [window.dimensions]
  columns = 70
  lines = 20

[font]
normal = { family = "CodeNewRomanNerdFont", style="Bold" }
size = 8
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[colors.normal]
black = "0x123e7c"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.bright]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x00ff00"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.dim]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[keyboard]

[[keyboard.bindings]]
key = "C"
mods = "Control|Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Alt"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "None"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "None"
